### ISSUE TITLE
generatemc errors

### ISSUE THREAD

**Issue by NatMoj** [DataMedSci/mcpartools#22]
[prometheus][plgnatada@login01 plgnatada]$ generatemc -j 1 -p 100 test_rw3.inp 
INFO:mcpartools.generator:Creating directory: 
Traceback (most recent call last):
  File "/net/software/local/python/2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/net/software/local/python/2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/net/archive/groups/plggccbmc/software/tools/mcpartools/0.1.3/generatemc/__main__.py", line 3, in <module>
  File "/net/archive/groups/plggccbmc/software/tools/mcpartools/0.1.3/generatemc/mcpartools/generatemc.py", line 71, in main
  File "/net/archive/groups/plggccbmc/software/tools/mcpartools/0.1.3/generatemc/mcpartools/generator.py", line 69, in run
  File "/net/archive/groups/plggccbmc/software/tools/mcpartools/0.1.3/generatemc/mcpartools/generator.py", line 89, in generate_main_dir
  File "/net/software/local/python/2.7.9/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)

**Comment by grzanka** [comment]
Note that this happends when no workspace directory is specified.
