### ISSUE TITLE
Particle number should be optional/obligatory?

### ISSUE THREAD

**Issue by ant6** [DataMedSci/mcpartools#50]
```
$ python mcpartools/generatemc.py -j 10 beam.inp
Traceback (most recent call last):
  File "mcpartools/generatemc.py", line 77, in <module>
    sys.exit(main(sys.argv[1:]))
  File "mcpartools/generatemc.py", line 71, in main
    ret_code = generator.run()
  File "/home/ant6/PycharmProjects/mcpartools/mcpartools/generator.py", line 84, in run
    self.generate_submit_script()
  File "/home/ant6/PycharmProjects/mcpartools/mcpartools/generator.py", line 136, in generate_submit_script
    self.scheduler.write_submit_script(script_path, self.options.jobs_no, self.workspace_dir)
  File "/home/ant6/PycharmProjects/mcpartools/mcpartools/scheduler/base.py", line 48, in write_submit_script
    fd.write(self.submit_script_body(jobs_no, abs_path_workspace))
  File "/home/ant6/PycharmProjects/mcpartools/mcpartools/scheduler/base.py", line 36, in submit_script_body
    script_path=script_path)
ValueError: Invalid conversion specification
```

**Comment by grzanka** [comment]
Particle number should be obligatory.
