### ISSUE TITLE
script templates missing from single binary generatemc file

### ISSUE THREAD

**Issue by grzanka** [DataMedSci/mcpartools#65]
I've downloaded https://github.com/DataMedSci/mcpartools/releases/download/v0.1.8/generatemc file
and tried to generate some stuff for SH12A config. It failed.

```
# plgkongruencj at login01.pro.cyfronet.pl in /net/scratch/people/plgkongruencj [23:52:52]
→ ./generatemc 2016_Grid_Phantom/SH12A/ -w a1
WARNING:mcpartools.generator:Workspace dir a1 doesn't exists, will be created.
Traceback (most recent call last):
  File "mcpartools/generatemc.py", line 83, in <module>
  File "mcpartools/generatemc.py", line 76, in main
  File "mcpartools/generator.py", line 71, in __init__
  File "mcpartools/mcengine/common.py", line 21, in get_mcengine
  File "mcpartools/mcengine/shieldhit.py", line 20, in __init__
  File "site-packages/pkg_resources/__init__.py", line 1215, in resource_string
  File "site-packages/pkg_resources/__init__.py", line 1457, in get_resource_string
  File "site-packages/pkg_resources/__init__.py", line 1530, in _get
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 474, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIUw5sZq/mcpartools/mcengine/data/run_shieldhit.sh'
Failed to execute script generatemc

# plgkongruencj at login01.pro.cyfronet.pl in /net/scratch/people/plgkongruencj [23:52:54]
→ ./generatemc --version                     
0.1.8
```

**Comment by ant6** [comment]
That's new I believe. I mean - I didn't test `-w` switch, so...

**Comment by grzanka** [comment]
I think this is related to packaging and pyinstaller
